### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [seL4/capdl-loader-app#1]
I would like to point out that identifiers like "[`__CAPDL_H__`](https://github.com/seL4/capdl-loader-app/blob/922aef4defe878882fa17b1a8e8e13094f956924/include/capdl.h#L11)" and "[`__CAPDL_SPEC_H__`](https://github.com/seL4/capdl-loader-app/blob/922aef4defe878882fa17b1a8e8e13094f956924/include/capdl_spec.h#L11)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Smattr** [comment]
As per my comments from seL4/camkes#1 and others.

**Comment by Smattr** [comment]
This issue was resolved in 2b860d1de1ca4dc896c3fa836fd5a91df20794b4. Can someone please close?

**Comment by elfring** [comment]
Would you also like to reconsider the use of the remaining [double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) in affected identifiers according to the naming convention of the C++ language standard?

**Comment by lsf37** [comment]
There is no C++ code in this repository, so I don't think that makes sense.

**Comment by elfring** [comment]
Would you like to support for your software that the corresponding source files can also be safely handled by C++ compilers?

**Comment by lsf37** [comment]
We do not. This software does not run in an environment that supports C++ and should not be used with a C++ compiler.
